# Generated by Django 2.1.5 on 2019-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('face', models.CharField(max_length=250)),
                ('insta', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
