# Generated by Django 2.1.5 on 2019-01-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
