# Generated by Django 2.1.5 on 2019-01-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190122_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('capa', models.ImageField(upload_to='')),
            ],
        ),
    ]
